export type Field = { key: string; label: string; type?: 'number' | 'textarea' | 'country' | 'state' | 'shipping' | 'active' | 'select' | 'secret'; required?: boolean; min?: number; max?: number; options?: string[] };
export type Section = { label: string; resource: string; fields: Field[]; columns: string[]; active?: boolean };
const name: Field = { key: 'name', label: 'Name', required: true };
const country: Field = { key: 'countryCode', label: 'Country', type: 'country', required: true };
const shipping: Field = { key: 'shippingType', label: 'Shipping method', type: 'shipping', required: true };
const active: Field = { key: 'isActive', label: 'Availability', type: 'active' };
const price: Field = { key: 'price', label: 'Price (USD)', type: 'number', required: true, min: 0 };
const dimensions: Field[] = ['width', 'height', 'depth'].map(key => ({ key, label: `${key[0].toUpperCase()}${key.slice(1)}`, type: 'number', required: true, min: 0.01 }));
const coordinates: Field[] = [{key:'latitude',label:'Latitude'}, {key:'longitude',label:'Longitude'}];
export const adminSections: Section[] = [
  {label:'Dashboard',resource:'dashboard',columns:[],fields:[]},
  {label:'Item Catalog',resource:'item-catalog',columns:[],fields:[]},
  {label:'Services',resource:'service',columns:['name','key','status','visibility'],fields:[name,{key:'key',label:'Service',type:'select',options:['ship-barrel','express-gifts','custom-cargo']},{key:'status',label:'Status',type:'select',options:['active','unavailable','coming-soon','suspended']},{key:'visibility',label:'Visibility',type:'select',options:['visible','hidden']}]},
  {label:'Routes',resource:'network-route',columns:['name','origin','destination','service','status','visibility'],fields:[name,{key:'origin',label:'Origin',type:'country',required:true},{key:'destination',label:'Destination',type:'country',required:true},{key:'service',label:'Service',type:'select',options:['ship-barrel','express-gifts','custom-cargo']},{key:'status',label:'Status',type:'select',options:['active','unavailable','coming-soon','suspended']},{key:'visibility',label:'Visibility',type:'select',options:['visible','hidden']}]},
  { label: 'Orders', resource: 'order', columns: ['name','price','status','isPaid','createdAt'], fields: [{...name,label:'Customer / shipment name'}, price,{key:'email',label:'Sender email'},{key:'phone',label:'Sender phone'},{key:'senderAddress',label:'Sender address',type:'textarea'},{key:'receiverName',label:'Receiver name'},{key:'receiverPhone',label:'Receiver phone'},{key:'receiverAddress',label:'Receiver address',type:'textarea'},{key:'description',label:'Contents',type:'textarea'}, {key:'notes',label:'Internal notes',type:'textarea'}] },
  { label: 'Products', resource: 'product', active:true, columns:['name','price','weight','isActive'], fields:[name,price,...dimensions,{key:'weight',label:'Weight (kg)',type:'number',required:true,min:0.01},active] },
  { label: 'Containers', resource:'container',active:true,columns:['description','countryCode','shippingType','price','isActive'],fields:[country,shipping,...dimensions,price,{key:'serviceCharge',label:'Service charge (USD)',type:'number',min:0},{key:'otherCharge',label:'Other charge (USD)',type:'number',min:0},{key:'otherChargeDescription',label:'Other charge description'},{key:'description',label:'Description',type:'textarea'},{key:'image',label:'Image URL (HTTPS)'},active] },
  { label:'Tax rates',resource:'tax-rate',columns:['name','countryCode','rate'],fields:[name,country,{key:'rate',label:'Tax rate (%)',type:'number',min:0,max:100,required:true}] },
  { label:'Documents',resource:'country-document',columns:['name','countryCode','shippingType','description'],fields:[name,country,shipping,{key:'description',label:'Requirement description',type:'textarea',required:true}] },
  { label:'Contacts',resource:'contact-us',columns:['name','email','subject','status','createdAt'],fields:[name,{key:'email',label:'Email',required:true},{key:'phone',label:'Phone',required:true},{key:'subject',label:'Subject',required:true},{key:'message',label:'Message',type:'textarea',required:true},{key:'status',label:'Handling status',type:'select',options:['new','in-progress','resolved']},{key:'notes',label:'Internal notes',type:'textarea'}] },
  { label:'Countries',resource:'country',active:true,columns:['name','isoCode','currency','isActive','canSendFrom','canDeliverTo'],fields:[name,{key:'isoCode',label:'ISO country code',required:true},{key:'phonecode',label:'Calling code',required:true},{key:'flag',label:'Flag',required:true},{key:'currency',label:'Currency code',required:true},...coordinates,active,{key:'canSendFrom',label:'Origin shipping',type:'active'},{key:'canDeliverTo',label:'Destination shipping',type:'active'}] },
  { label:'States',resource:'state',active:true,columns:['name','isoCode','countryCode','isActive'],fields:[name,{key:'isoCode',label:'State code',required:true},country,...coordinates,active] },
  { label:'Cities',resource:'city',active:true,columns:['name','countryCode','stateCode','isActive'],fields:[name,country,{key:'stateCode',label:'State / province',type:'state',required:true},...coordinates,active] },
  { label:'Settings',resource:'global-settings',columns:['name','slug','type','value'],fields:[name,{key:'slug',label:'Setting key',required:true},{key:'type',label:'Visibility',type:'select',options:['private','public']},{key:'value',label:'Value',type:'secret'}] },
];
export const columnLabels: Record<string,string> = {key:'Service key',origin:'Origin',destination:'Destination',service:'Service',visibility:'Visibility',name:'Name',price:'Price',status:'Status',isPaid:'Payment',createdAt:'Created',weight:'Weight',isActive:'Availability',countryCode:'Country',shippingType:'Shipping method',description:'Description',rate:'Rate',email:'Email',subject:'Subject',isoCode:'Code',currency:'Currency',stateCode:'State',slug:'Setting key',type:'Visibility',value:'Value',canSendFrom:'Origin',canDeliverTo:'Destination'};
export type AdminItem = { _id: string; [key:string]: unknown };
export type AdminPage = { items: AdminItem[]; totalRecords:number; page:number; pageSize:number };


