import { ChangeEvent, FormEvent, useMemo, useState } from 'react';
import { ImagePlus, Pencil, Plus, Trash2, X } from 'lucide-react';
import { CatalogItem, CatalogVariant, loadCatalog, money, saveCatalog } from './catalog';

type ServiceTab='ship-barrel'|'express-gifts';
const serviceLabel:Record<ServiceTab,string>={'ship-barrel':'Container Shipping','express-gifts':'Gift Shop'};
const countryOptions=['ET','US','AE','IN','NG','KE','GH','GB','CA','CN','TR','ZA'];
const blank=(service:ServiceTab):CatalogItem=>({id:crypto.randomUUID(),service,name:'',category:'',price:0,weightLb:service==='ship-barrel'?1:undefined,volumeIn3:service==='ship-barrel'?1:undefined,deliverySpeed:service==='express-gifts'?'Same Day':undefined,ownItem:false,status:'live',countries:[],variants:[]});

export default function ItemCatalogAdmin(){
 const [tab,setTab]=useState<ServiceTab>('ship-barrel');const [items,setItems]=useState(loadCatalog);const [editing,setEditing]=useState<string|null>(null);const [adding,setAdding]=useState(false);
 const visible=items.filter(i=>i.service===tab);function persist(next:CatalogItem[]){setItems(next);saveCatalog(next)}
 function upsert(item:CatalogItem){persist(items.some(i=>i.id===item.id)?items.map(i=>i.id===item.id?item:i):[item,...items]);setEditing(null);setAdding(false)}
 function remove(id:string){if(confirm('Permanently delete this item?'))persist(items.filter(i=>i.id!==id))}
 function setImage(item:CatalogItem,file?:File){if(!file)return;const reader=new FileReader();reader.onload=()=>upsert({...item,image:String(reader.result)});reader.readAsDataURL(file)}
 return <div className="admin-main"><div className="admin-top"><div><span className="eyebrow">Catalog control</span><h1>Item Catalog</h1><p>Manage barrel packing items and express gift products independently. Photos and quick edits are stored in this browser.</p></div><button className="button" onClick={()=>setAdding(true)}><Plus size={16}/> Add Item</button></div><div className="catalog-tabs">{(Object.keys(serviceLabel) as ServiceTab[]).map(key=><button key={key} className={tab===key?'active':''} onClick={()=>{setTab(key);setAdding(false);setEditing(null)}}>{serviceLabel[key]}</button>)}</div>{adding&&<CatalogEditor item={blank(tab)} onSave={upsert} onCancel={()=>setAdding(false)}/>}<div className="catalog-grid">{visible.map(item=>editing===item.id?<CatalogEditor key={item.id} item={item} onSave={upsert} onCancel={()=>setEditing(null)}/>:<article className={item.status==='hidden'?'catalog-card hidden-card':'catalog-card'} key={item.id}><div className="catalog-photo">{item.image?<img src={item.image} alt=""/>:<ImagePlus/>}<label><ImagePlus size={18}/> {item.image?'Change Photo':'Upload Photo'}<input type="file" accept="image/*" onChange={(e:ChangeEvent<HTMLInputElement>)=>setImage(item,e.target.files?.[0])}/></label>{item.image&&<button className="photo-remove" onClick={()=>upsert({...item,image:''})}><X size={14}/></button>}</div><div className="catalog-card-body"><div className="catalog-card-head"><span>{item.category}</span><button className={item.status==='live'?'live':'hidden'} onClick={()=>upsert({...item,status:item.status==='live'?'hidden':'live'})}>{item.status==='live'?'Live':'Hidden'}</button></div><h3>{item.name}</h3><p>{priceLabel(item)} {item.ownItem&&<b> · own item</b>}</p>{item.service==='ship-barrel'?<small>{item.weightLb||0} lb · {item.volumeIn3||0} in³</small>:<small>{item.deliverySpeed}</small>}<div className="size-badges">{item.variants.map(v=><span key={v.id}>{v.label}</span>)}</div><p className="country-line">{item.countries.length?item.countries.join(' · '):'All countries'}</p><div className="catalog-actions"><button onClick={()=>setEditing(item.id)}><Pencil size={15}/> Edit</button><button onClick={()=>remove(item.id)}><Trash2 size={15}/> Delete</button></div></div></article>)}</div></div>
}
function priceLabel(item:CatalogItem){if(item.ownItem)return 'Own item';const prices=[item.price,...item.variants.map(v=>v.price)].filter(v=>v>0);return prices.length>1&&Math.min(...prices)!==Math.max(...prices)?`From ${money(Math.min(...prices))}`:money(item.price)}
function CatalogEditor({item,onSave,onCancel}:{item:CatalogItem;onSave:(item:CatalogItem)=>void;onCancel:()=>void}){const [draft,setDraft]=useState<CatalogItem>(item);const [variant,setVariant]=useState<CatalogVariant>({id:'',label:'',description:'',price:0,weightLb:0,volumeIn3:0});const isGift=draft.service==='express-gifts';const selected=useMemo(()=>new Set(draft.countries),[draft.countries]);function submit(e:FormEvent){e.preventDefault();onSave(draft)}function toggleCountry(code:string){const next=new Set(selected);next.has(code)?next.delete(code):next.add(code);setDraft({...draft,countries:[...next]})}function addVariant(){if(!variant.label)return;setDraft({...draft,variants:[...draft.variants,{...variant,id:crypto.randomUUID()}]});setVariant({id:'',label:'',description:'',price:0,weightLb:0,volumeIn3:0})}
 return <form className="catalog-editor panel" onSubmit={submit}><div className="two"><label>Name<input required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Category<input required value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}/></label></div><div className="two"><label>Base price<input type="number" min="0" step="any" value={draft.price} disabled={draft.ownItem} onChange={e=>setDraft({...draft,price:Number(e.target.value)})}/></label>{isGift?<label>Delivery speed<select value={draft.deliverySpeed||'Same Day'} onChange={e=>setDraft({...draft,deliverySpeed:e.target.value})}>{['Same Day','Express','Standard','Scheduled'].map(v=><option key={v}>{v}</option>)}</select></label>:<label>Customer owns this item<select value={draft.ownItem?'yes':'no'} onChange={e=>setDraft({...draft,ownItem:e.target.value==='yes',price:e.target.value==='yes'?0:draft.price})}><option value="no">No</option><option value="yes">Yes</option></select></label>}</div>{!isGift&&<div className="two"><label>Weight (lb)<input type="number" min="0" step="any" value={draft.weightLb||0} onChange={e=>setDraft({...draft,weightLb:Number(e.target.value)})}/></label><label>Volume (in³)<input type="number" min="0" step="any" value={draft.volumeIn3||0} onChange={e=>setDraft({...draft,volumeIn3:Number(e.target.value)})}/></label></div>}<h3>Size Options</h3><div className="variant-list">{draft.variants.map(v=><span key={v.id}>{v.label} · {money(v.price)} <button type="button" onClick={()=>setDraft({...draft,variants:draft.variants.filter(x=>x.id!==v.id)})}>×</button></span>)}</div><div className="variant-form"><input placeholder="Label" value={variant.label} onChange={e=>setVariant({...variant,label:e.target.value})}/><input placeholder="Explanation" value={variant.description} onChange={e=>setVariant({...variant,description:e.target.value})}/><input type="number" placeholder="Price" value={variant.price} onChange={e=>setVariant({...variant,price:Number(e.target.value)})}/>{!isGift&&<><input type="number" placeholder="Weight lb" value={variant.weightLb} onChange={e=>setVariant({...variant,weightLb:Number(e.target.value)})}/><input type="number" placeholder="Volume in³" value={variant.volumeIn3} onChange={e=>setVariant({...variant,volumeIn3:Number(e.target.value)})}/></>}<button type="button" onClick={addVariant}>+ Add Size</button></div><h3>Country Availability</h3><div className="country-tools"><button type="button" onClick={()=>setDraft({...draft,countries:countryOptions})}>All</button><button type="button" onClick={()=>setDraft({...draft,countries:[]})}>None / all countries</button></div><div className="country-chips">{countryOptions.map(code=><button type="button" className={selected.has(code)?'active':''} key={code} onClick={()=>toggleCountry(code)}>{code}</button>)}</div><div className="actions"><button className="button">Save item</button><button type="button" onClick={onCancel}>Cancel</button></div></form>
}

